### ISSUE TITLE
Google Chrome Version not supported

### ISSUE THREAD

**Issue by thePhenom21** [hruzgar/artemis-dl#9]
Hi Hasan. I was trying to use your program with the pre configured executable on Windows but I faced an issue. I guess there are some dependency issues between the latest version of Google Chrome and Selenium. Here is the error message I got.
<img width="835" alt="Screenshot 2023-08-24 125200" src="https://github.com/hruzgar/artemis-dl/assets/65731277/054cfc46-8906-47d2-bb3e-6227489d663b">

**Comment by thePhenom21** [comment]
Using Selenium version 4.11.2 (the current latest on pypi website) fixed the issue.

**Comment by hruzgar** [comment]
Oh yeah. Selenium needs to be updated. How did you update selenium from the binary? lol. Thanks for the reminder though. Will fix this when I'm back at home

**Comment by thePhenom21** [comment]
I actually didn't update the binary, just tried building the project with the latest Selenium version
